# Generated by Django 4.2.1 on 2024-03-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Указывается телеграм ID после аутентификации', null=True, unique=True, verbose_name='Телеграм ID')),
                ('login', models.CharField(help_text='Укажите логин для ученика', max_length=30, unique=True, verbose_name='Логин в базе данных')),
                ('password', models.CharField(help_text='Укажите пароль для ученика', max_length=30, verbose_name='Пароль в базе данных')),
                ('full_name', models.CharField(help_text='Укажите ФИО ученика', max_length=45, verbose_name='ФИО')),
                ('if_fourteen', models.BooleanField(default=False, help_text='Укажите достиг ли ученик 14-го возраста', verbose_name='Достиг ли ученик 14-го возраста')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
