# Generated by Django 4.2.1 on 2024-03-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_teacher_alter_studentcontentdetails_date_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Укажите название дисцпиплины', max_length=50, unique=True, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(help_text='Укажите ФИО преподавателя', max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='login',
            field=models.CharField(help_text='Укажите логин для преподавателя', max_length=30, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(help_text='Укажите пароль для преподавателя', max_length=30, verbose_name='Пароль'),
        ),
    ]
