# Generated by Django 4.2.1 on 2024-03-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_alter_studentgroup_options_studentgroup_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название кабинета', max_length=50, verbose_name='Название кабинета')),
            ],
        ),
    ]
