# Generated by Django 4.2.1 on 2024-03-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
    ]
