# Generated by Django 4.2.1 on 2024-03-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_alter_classroom_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='teacher',
            field=models.ForeignKey(help_text='Укажите преподавателя, который преподает дисциплину', null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.teacher', verbose_name='Преподаватель'),
        ),
    ]
