# Generated by Django 4.2.1 on 2024-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_authentication',
            field=models.BooleanField(blank=True, default=False, help_text='Состояние аутентификации', verbose_name='Аутентификация'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_authentication',
            field=models.BooleanField(blank=True, default=False, help_text='Состояние аутентификации', verbose_name='Аутентификация'),
        ),
    ]
