# Generated by Django 5.0.3 on 2024-06-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_student_is_authentication_teacher_is_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.BinaryField(help_text='Укажите логин для ученика', unique=True, verbose_name='Логин'),
        ),
    ]
