# Generated by Django 5.0.3 on 2024-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0013_alter_student_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.CharField(help_text='Укажите логин для ученика', max_length=256, unique=True, verbose_name='Логин'),
        ),
    ]
