# Generated by Django 5.0.3 on 2024-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_alter_student_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.CharField(help_text='Укажите логин для ученика', max_length=30, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='date_birth',
            field=models.DateField(blank=True, help_text='Укажите дату рождения', null=True, verbose_name='Дата рождения'),
        ),
    ]
