# Generated by Django 5.0.3 on 2024-06-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0015_alter_student_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='name_education_organization',
            field=models.CharField(blank=True, help_text='Укажите название учебной организации', max_length=255, null=True, verbose_name='Учебная организация'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='parent_contact',
            field=models.CharField(blank=True, help_text='Укажите контактные данные родителя (номер телефона, эл. почта)', max_length=255, null=True, verbose_name='Контактные данные родителя'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='parent_residential_adress',
            field=models.CharField(blank=True, help_text='Укажите место регистрации родителя (законного представителя)', max_length=255, null=True, verbose_name='Место регистрации родителя'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='passport_data',
            field=models.CharField(blank=True, help_text='Укажите паспортные данные(номер, серия)', max_length=255, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='passport_data_date_of_issueс',
            field=models.DateField(blank=True, help_text='Укажите дату выдачи паспорта', null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='passport_data_issued_by',
            field=models.CharField(blank=True, help_text='Укажите кем выдан паспорт', max_length=255, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='student_contact',
            field=models.CharField(blank=True, help_text='Укажите контактные данные родителя (номер телефона, эл. почта)', max_length=255, null=True, verbose_name='Контактные данные ученика'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='student_residential_adress',
            field=models.CharField(blank=True, help_text='Укажите адрес проживания с индексом', max_length=255, null=True, verbose_name='Адрес проживания'),
        ),
    ]
