# Generated by Django 5.0.3 on 2024-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0016_alter_studentcontentdetails_name_education_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='certificate_number',
            field=models.CharField(help_text='Укажите номер сертификата', max_length=255, unique=True, verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='parent_full_name',
            field=models.CharField(blank=True, help_text='Укажите ФИО Родителя (законного представителя)', max_length=255, null=True, verbose_name='ФИО Родителя'),
        ),
    ]
