# Generated by Django 5.0.3 on 2024-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0017_alter_studentcontentdetails_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='date_birth',
            field=models.CharField(blank=True, help_text='Укажите дату рождения', max_length=255, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='date_contract',
            field=models.CharField(help_text='Укажите дату заключения контракта', max_length=255, verbose_name='Дата заключения контракта'),
        ),
        migrations.AlterField(
            model_name='studentcontentdetails',
            name='passport_data_date_of_issueс',
            field=models.CharField(blank=True, help_text='Укажите дату выдачи паспорта', max_length=255, null=True, verbose_name='Дата выдачи'),
        ),
    ]
